name: tmp
channels:
  - <unknown>
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py39h06a4308_0
  - pyrosetta=2021.16+release.8ee4f02=py38_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.85
      - biotite==0.39.0
      - certifi==2025.1.31
      - charset-normalizer==2.0.12
      - click==8.1.8
      - cmake==4.0.0
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.5.0
      - decorator==5.1.0
      - deepspeed==0.5.9
      - dgl==0.9.1
      - dgl-cu113==0.9.1
      - diffusers==0.35.2
      - dill==0.3.8
      - dllogger==1.1.0
      - dm-tree==0.1.6
      - docker-pycreds==0.4.0
      - dtaidistance==2.3.13
      - e3nn==0.3.3
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - fair-esm==2.0.1
      - fasteners==0.19
      - filelock==3.18.0
      - fonttools==4.57.0
      - freesasa==2.2.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - griddataformats==1.0.2
      - haddock3==2025.11.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - joypy==0.2.6
      - jsonpickle==4.1.1
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - lit==18.1.8
      - lxml==6.0.2
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mda-xdrlib==0.2.0
      - mdanalysis==2.7.0
      - ml-collections==0.1.0
      - mmtf-python==1.1.3
      - modlamp==4.3.2
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - msgpack==1.1.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - mysql-connector-python==9.4.0
      - narwhals==2.15.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nose==1.3.7
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - packaging==24.2
      - pandas==2.2.3
      - pdb-tools==2.5.0
      - pillow==11.1.0
      - platformdirs==4.3.7
      - plotly==6.4.0
      - prodigy-lig==1.1.4
      - prodigy-prot==2.3.0
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pynvml==11.0.0
      - pyparsing==3.2.3
      - pyrsistent==0.20.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tokenizers==0.20.3
      - toml==0.10.2
      - torch==1.12.0+cu113
      - torch-geometric==2.6.1
      - torchmetrics==0.11.0
      - torchvision==0.13.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.0.0
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - wandb==0.19.9
      - xgboost==2.1.4
      - xxhash==3.5.0
      - yarl==1.19.0
      - zipp==3.21.0
prefix: /wangchuanshi/miniconda3/envs/tmp
